<?php

if (!defined('B_PROLOG_INCLUDED') || B_PROLOG_INCLUDED !== true) {
    die();
}

$indexPageOptions = $GLOBALS['arTheme']['INDEX_TYPE']['SUB_PARAMS'][$GLOBALS['arTheme']['INDEX_TYPE']['VALUE']];
$blockOptions = $indexPageOptions['TARIFFS'];
$blockTemplateOptions = $blockOptions['TEMPLATE']['LIST'][$blockOptions['TEMPLATE']['VALUE']];
$bTariffsUseDetail = $GLOBALS['arTheme']['TARIFFS_USE_DETAIL']['VALUE'] === 'Y';

$tabs = $blockOptions["INDEX_BLOCK_OPTIONS"]["BOTTOM"]["TABS"]["VALUE"];
$defaultPriceKey = $tabs === 'TOP' ? ($_REQUEST['tariffs_price_key'] ?? 'DEFAULT') : 'DEFAULT';
if ($tabs === 'TOP') {
    $GLOBALS['arFrontFilter']['!PROPERTY_TARIF_PRICE_' . $defaultPriceKey] = false;
}

$APPLICATION->IncludeComponent(
    "bitrix:news.list",
    "tariffs-list",
    [
        "IBLOCK_TYPE"                     => "aspro_allcorp3_catalog",
        "IBLOCK_ID"                       => "35",
        "NEWS_COUNT"                      => "5",
        "SORT_BY1"                        => "SORT",
        "SORT_ORDER1"                     => "ASC",
        "SORT_BY2"                        => "ID",
        "SORT_ORDER2"                     => "DESC",
        "FILTER_NAME"                     => "arFrontFilter",
        "FIELD_CODE"                      => [
            0 => "NAME",
            1 => "PREVIEW_TEXT",
            2 => "PREVIEW_PICTURE",
            3 => "",
        ],
        "PROPERTY_CODE"                   => [
            0  => "MIN_VES",
            1  => "FORM_ORDER",
            2  => "STRAHOVANIE",
            3  => "DOSTAVKA_OT",
            4  => "HIT",
            5  => "PRICE_CURRENCY",
            6  => "TARIF_PRICE_1",
            7  => "TARIF_PRICE_2",
            8  => "TARIF_PRICE_2_DISC",
            9  => "TARIF_PRICE_3",
            10 => "TARIF_PRICE_3_DISC",
            11 => "TARIF_PRICE_DEFAULT",
            12 => "TARIF_PRICE_DEFAULT_DISC",
            13 => "TARIF_ITEM",
            14 => "MULTI_PROP",
            15 => "SUPPLIED",
            16 => "USERS",
            17 => "EXTENSION",
            18 => "DURATION",
            19 => "GROUPS_USERS",
            20 => "ADMIN",
            21 => "VOLUME",
            22 => "FILE_STORAGE",
            23 => "MEMORY",
            24 => "CPU",
            25 => "IP",
            26 => "HOSTING_SITES",
            27 => "KOLLICHESTVO_BAZ_DANNIX",
            28 => "ZADACHI",
            29 => "NAGRUZKA",
            30 => "ONLY_ONE_PRICE",
            31 => "MULTI_PROP_BOTTOM_PROPS",
            32 => "TASK",
            33 => "ONLINE",
            34 => "MESSAGE",
            35 => "UPDATES",
            36 => "LANGUAGES",
            37 => "TARIF_PRICE_1_DISC",
            38 => "TARIF_PRICE_4",
            39 => "ICON",
            40 => "VISA",
            41 => "NUM_DEVICES",
            42 => "APPLE",
            43 => "ELPURSE",
            44 => "API_INTEGRATION",
            45 => "SIEM_SYSTEM",
            46 => "COLLECT_INFO",
            47 => "RULES_SIGNAT",
            48 => "SCANNER",
            49 => "ANTIVIRUS",
            50 => "PROTECT_PAYMENT",
            51 => "PROTECT_CAMERA",
            52 => "ANTIVOR",
            53 => "CONTROL",
            54 => "SUPPORT_FREE",
            55 => "GUARANTEE",
            56 => "BLOCKING_SITES",
            57 => "BLOCKING_TRAFFIC",
            58 => "SECURITY",
            59 => "PROTECT_CHILDREN",
            60 => "SUM_FINANCING",
            61 => "TERM_LEASING",
            62 => "INSURANCE",
            63 => "CURRENCY",
            64 => "ADVANCE_PAY",
            65 => "RATE",
            66 => "PERCENTAGE",
            67 => "PAYMENTS",
            68 => "SUPPORT",
            69 => "NOTIFICATION",
            70 => "TURN",
            71 => "",
        ],
        "CHECK_DATES"                     => "Y",
        "DETAIL_URL"                      => "",
        "AJAX_MODE"                       => "N",
        "AJAX_OPTION_JUMP"                => "N",
        "AJAX_OPTION_STYLE"               => "Y",
        "AJAX_OPTION_HISTORY"             => "N",
        "CACHE_TYPE"                      => "A",
        "CACHE_TIME"                      => "3600000",
        "CACHE_FILTER"                    => "Y",
        "CACHE_GROUPS"                    => "Y",
        "PREVIEW_TRUNCATE_LEN"            => "",
        "ACTIVE_DATE_FORMAT"              => "j F Y",
        "SET_TITLE"                       => "N",
        "SET_STATUS_404"                  => "N",
        "INCLUDE_IBLOCK_INTO_CHAIN"       => "N",
        "ADD_SECTIONS_CHAIN"              => "N",
        "HIDE_LINK_WHEN_NO_DETAIL"        => "N",
        "PARENT_SECTION"                  => "",
        "PARENT_SECTION_CODE"             => "",
        "INCLUDE_SUBSECTIONS"             => "N",
        "PAGER_TEMPLATE"                  => "ajax",
        "DISPLAY_TOP_PAGER"               => "N",
        "DISPLAY_BOTTOM_PAGER"            => "Y",
        "PAGER_TITLE"                     => "",
        "PAGER_SHOW_ALWAYS"               => "N",
        "PAGER_DESC_NUMBERING"            => "N",
        "PAGER_DESC_NUMBERING_CACHE_TIME" => "3600000",
        "PAGER_SHOW_ALL"                  => "N",
        "AJAX_OPTION_ADDITIONAL"          => "",
        "SET_BROWSER_TITLE"               => "N",
        "SET_META_KEYWORDS"               => "N",
        "SET_META_DESCRIPTION"            => "N",
        "COMPONENT_TEMPLATE"              => "tariffs-list",
        "SET_LAST_MODIFIED"               => "N",
        "STRICT_SECTION_CHECK"            => "Y",
        "SHOW_DETAIL_LINK"                => "Y",
        "PAGER_BASE_LINK_ENABLE"          => "N",
        "SHOW_404"                        => "N",
        "MESSAGE_404"                     => "",
        "SHOW_DATE"                       => "N",
        "COUNT_IN_LINE"                   => "4",
        "USE_DETAIL"                      => $bTariffsUseDetail ? "Y" : "N",
        "VISIBLE_PROP_COUNT"              => "4",
        "ROW_VIEW"                        => false,
        "BORDER"                          => true,
        "ITEM_HOVER_SHADOW"               => true,
        "DARK_HOVER"                      => false,
        "ROUNDED"                         => true,
        "ROUNDED_IMAGE"                   => false,
        "ELEMENTS_ROW"                    => "4",
        "MAXWIDTH_WRAP"                   => true,
        "MOBILE_SCROLLED"                 => false,
        "HIDE_PAGINATION"                 => "N",
        "SLIDER"                          => true,
        "GRID_GAP"                        => $blockTemplateOptions["ADDITIONAL_OPTIONS"]["ITEMS_OFFSET"]["VALUE"] == "Y" ? 32 : 0,
        "DOTS_0"                          => "Y",
        "ITEM_0"                          => "1",
        "DOTS_380"                        => "Y",
        "ITEM_380"                        => "1",
        "DOTS_768"                        => "N",
        "ITEM_768"                        => "2",
        "DOTS_1200"                       => "N",
        "ITEM_1200"                       => "4",
        "VIEW_TYPE"                       => "type_1",
        "ORDER_VIEW"                      => CAllcorp3::GetFrontParametrValue("ORDER_VIEW") == "Y",
        "NARROW"                          => $blockTemplateOptions["ADDITIONAL_OPTIONS"]["WIDE"]["VALUE"] != "Y",
        "ITEMS_OFFSET"                    => $blockTemplateOptions["ADDITIONAL_OPTIONS"]["ITEMS_OFFSET"]["VALUE"] == "Y",
        "IMAGES"                          => "BIG_PICTURES",
        "HIDE_LEFT_TEXT_BLOCK"            => "Y",
        "TABS"                            => $tabs,
        "DEFAULT_PRICE_KEY"               => $defaultPriceKey,
        "SHOW_TITLE"                      => $blockOptions["INDEX_BLOCK_OPTIONS"]["BOTTOM"]["SHOW_TITLE"]["VALUE"] == "Y",
        "TITLE_POSITION"                  => $blockOptions["INDEX_BLOCK_OPTIONS"]["BOTTOM"]["TITLE_POSITION"]["VALUE"],
        "TITLE"                           => "Виды Доставки",
        "RIGHT_TITLE"                     => "",
        "RIGHT_LINK"                      => "",
        "CHECK_REQUEST_BLOCK"             => CAllcorp3::checkRequestBlock("tariffs"),
        "IS_AJAX"                         => CAllcorp3::checkAjaxRequest(),
        "NAME_SIZE"                       => $blockTemplateOptions["ADDITIONAL_OPTIONS"]["WIDE"]["VALUE"] == "Y" ? 20 : 18,
        "SUBTITLE"                        => "",
        "SHOW_PREVIEW_TEXT"               => "N",
        "COMPOSITE_FRAME_MODE"            => "A",
        "COMPOSITE_FRAME_TYPE"            => "AUTO",
    ],
    false
);