<?php

require($_SERVER["DOCUMENT_ROOT"] . "/bitrix/header.php");
$APPLICATION->SetPageProperty("MENU", "Y");

$APPLICATION->SetTitle("Полезные статьи о работе с Китаем и не только от компании Дядя Лайфу");

$APPLICATION->SetPageProperty(
    "title",
    "Полезные статьи о работе с Китаем и не только от компании Дядя Лайфу"
);

$APPLICATION->SetPageProperty(
    "description",
    "Что может пойти не так, при работе с Китаем? Прочитать интересные статьи, получить ответы на возможные вопросы и узнать полезное вместе с Дядя Лайфу"
);

$APPLICATION->SetPageProperty("BLOG_PAGE", "Y");

$APPLICATION->IncludeComponent(
	"bitrix:news", 
	"blog", 
	array(
		"ADD_ELEMENT_CHAIN" => "Y",
		"ADD_SECTIONS_CHAIN" => "Y",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"BIG_GALLERY_PROP_CODE" => "PHOTOS",
		"BROWSER_TITLE" => "-",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"CACHE_TIME" => "36000000",
		"CACHE_TYPE" => "A",
		"CHECK_DATES" => "Y",
		"COMPOSITE_FRAME_MODE" => "A",
		"COMPOSITE_FRAME_TYPE" => "AUTO",
		"DETAIL_ACTIVE_DATE_FORMAT" => "",
		"DETAIL_BLOCKS_ALL_ORDER" => "desc,tizers,char,sale,reviews,big_gallery,video,docs,faq,services,projects,news,articles,staff,partners,vacancy,goods,dops,comments",
		"DETAIL_BLOCKS_ORDER" => "tizers,tabs,big_gallery,services,projects,news,articles,staff,partners,vacancy,goods,comments",
		"DETAIL_BLOCKS_TAB_ORDER" => "desc,char,video,docs,faq,reviews,dops",
		"DETAIL_DISPLAY_BOTTOM_PAGER" => "Y",
		"DETAIL_DISPLAY_TOP_PAGER" => "N",
		"DETAIL_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"DETAIL_PAGER_SHOW_ALL" => "Y",
		"DETAIL_PAGER_TEMPLATE" => "",
		"DETAIL_PAGER_TITLE" => "Страница",
		"DETAIL_PROPERTY_CODE" => array(
			0 => "VIDEO_IFRAME",
			1 => "LINK_ARTICLES",
			2 => "LINK_SALE",
			3 => "LINK_FAQ",
			4 => "AUTHOR",
			5 => "DATA",
			6 => "TASK_PROJECT",
			7 => "SITE",
			8 => "ORDERER",
			9 => "FORM_QUESTION",
			10 => "FORM_ORDER",
			11 => "PRICE",
			12 => "PRICEOLD",
			13 => "ECONOMY",
			14 => "LINK_STUDY",
			15 => "FOR_SHOW_1",
			16 => "FOR_SHOW_5",
			17 => "FOR_SHOW_2",
			18 => "FOR_SHOW_3",
			19 => "FOR_SHOW_4",
			20 => "FOR_SHOW_6",
			21 => "FOR_SHOW_7",
			22 => "FOR_SHOW_8",
			23 => "DOCUMENTS",
			24 => "PHOTOS",
			25 => "STATUS",
			26 => "ARTICLE",
			27 => "DATE_COUNTER",
			28 => "LINK_SKU",
			29 => "PRICE_CURRENCY",
			30 => "DEPTH",
			31 => "GRUZ_STRELI",
			32 => "GRUZ",
			33 => "DLINA_STRELI",
			34 => "VOLUME",
			35 => "RECOMMEND",
			36 => "SPEED",
			37 => "WIDTH_PROHOD",
			38 => "WIDTH_PROEZD",
			39 => "",
		),
		"DETAIL_SET_CANONICAL_URL" => "N",
		"DETAIL_USE_COMMENTS" => "N",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"DISPLAY_DATE" => "Y",
		"DISPLAY_NAME" => "Y",
		"DISPLAY_PICTURE" => "Y",
		"DISPLAY_PREVIEW_TEXT" => "Y",
		"DISPLAY_TOP_PAGER" => "N",
		"DOCS_PROP_CODE" => "DOCUMENTS",
		"ELEMENT_TYPE_VIEW" => "element_1",
		"HIDE_LINK_WHEN_NO_DETAIL" => "N",
		"IBLOCK_ID" => "37",
		"IBLOCK_TYPE" => "aspro_allcorp3_content",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
		"INCLUDE_SUBSECTIONS" => "Y",
		"LIST_ACTIVE_DATE_FORMAT" => "j F Y",
		"LIST_FIELD_CODE" => array(
			0 => "ID",
			1 => "NAME",
			2 => "PREVIEW_TEXT",
			3 => "PREVIEW_PICTURE",
			4 => "DATE_ACTIVE_FROM",
			5 => "",
		),
		"LIST_PROPERTY_CODE" => array(
			0 => "VIDEO_IFRAME",
			1 => "LINK_ARTICLES",
			2 => "LINK_SALE",
			3 => "LINK_FAQ",
			4 => "POSITION_BLOCK",
			5 => "PERIOD",
			6 => "",
		),
		"MESSAGE_404" => "",
		"META_DESCRIPTION" => "-",
		"META_KEYWORDS" => "-",
		"NEWS_COUNT" => "20",
		"NUM_DAYS" => "30",
		"NUM_NEWS" => "20",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => "main",
		"PAGER_TITLE" => "Новости",
		"PREVIEW_TRUNCATE_LEN" => "",
		"PROPERTIES_DISPLAY_TYPE" => "TABLE",
		"SECTION_ELEMENTS_TYPE_VIEW" => "FROM_MODULE",
		"SEF_FOLDER" => "/articles/",
		"SEF_MODE" => "Y",
		"SET_LAST_MODIFIED" => "N",
		"SET_STATUS_404" => "Y",
		"SET_TITLE" => "Y",
		"SHOW_404" => "Y",
		"SHOW_BIG_GALLERY" => "Y",
		"SHOW_DETAIL_LINK" => "Y",
		"SHOW_DOPS" => "N",
		"SORT_BY1" => "ACTIVE_FROM",
		"SORT_BY2" => "SORT",
		"SORT_ORDER1" => "DESC",
		"SORT_ORDER2" => "ASC",
		"STRICT_SECTION_CHECK" => "N",
		"TOP_GALLERY_PROP_CODE" => "-",
		"TYPE_BIG_GALLERY" => "SMALL",
		"T_ARTICLES" => "Интересное для вас",
		"T_BIG_GALLERY" => "Фото реальных отгрузок",
		"T_CHAR" => "",
		"T_DESC" => "",
		"T_DOCS" => "",
		"T_FAQ" => "Часто задаваемые вопросы",
		"T_GOODS" => "",
		"T_NEWS" => "",
		"T_PARTNERS" => "",
		"T_PROJECTS" => "",
		"T_REVIEWS" => "",
		"T_SALE" => "Действующие акции",
		"T_SERVICES" => "",
		"T_STAFF" => "",
		"T_VACANCY" => "",
		"T_VIDEO" => "",
		"USE_CATEGORIES" => "N",
		"USE_FILTER" => "N",
		"USE_PERMISSIONS" => "N",
		"USE_RATING" => "N",
		"USE_RSS" => "N",
		"USE_SEARCH" => "N",
		"USE_SHARE" => "Y",
		"YANDEX" => "N",
		"COMPONENT_TEMPLATE" => "blog",
		"T_DOPS" => "",
		"DETAIL_BLOG_USE" => "N",
		"DETAIL_BLOG_URL" => "catalog_comments",
		"COMMENTS_COUNT" => "5",
		"DETAIL_BLOG_TITLE" => "Комментарии",
		"DETAIL_BLOG_EMAIL_NOTIFY" => "N",
		"DETAIL_VK_USE" => "N",
		"DETAIL_FB_USE" => "N",
		"SHOW_CATEGORY" => "Y",
		"DETAIL_USE_TAGS" => "Y",
		"FILTER_NAME" => "",
		"FILTER_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"FILTER_PROPERTY_CODE" => array(
			0 => "",
			1 => "",
		),
		"SKU_IBLOCK_ID" => "21",
		"SKU_PROPERTY_CODE" => array(
			0 => "FORM_ORDER",
			1 => "STATUS",
			2 => "ARTICLE",
			3 => "PRICE_CURRENCY",
			4 => "PRICE",
			5 => "PRICEOLD",
			6 => "ECONOMY",
			7 => "COLOR",
			8 => "GOST",
			9 => "DLINA",
			10 => "VYLET_STRELY",
			11 => "MARK_STEEL",
			12 => "WIDTH",
		),
		"SKU_TREE_PROPS" => array(
			0 => "COLOR",
			1 => "DIAMETER",
			2 => "DLINA",
			3 => "VYLET_STRELY",
			4 => "THICKNESS_STEEL",
			5 => "WIDTH",
		),
		"SKU_SORT_FIELD" => "sort",
		"SKU_SORT_ORDER" => "asc",
		"SKU_SORT_FIELD2" => "name",
		"SKU_SORT_ORDER2" => "asc",
		"USE_REVIEW" => "N",
		"FILE_404" => "",
		"IMAGE_POSITION" => "left",
		"COUNT_IN_LINE" => "3",
		"ELEMENTS_ITEMS_OFFSET" => "Y",
		"ELEMENTS_COUNT" => "3",
		"SEF_URL_TEMPLATES" => array(
			"news" => "",
			"section" => "#SECTION_CODE_PATH#/",
			"detail" => "#SECTION_CODE_PATH#/#ELEMENT_CODE#/",
		)
	),
	false
);

require($_SERVER["DOCUMENT_ROOT"] . "/bitrix/footer.php");